FROM node:lts

RUN npm config set registry http://registry.npm.taobao.org/
RUN npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass
RUN npm i -g npm 
RUN npm i -g typescript webpack webpack-cli eslint