ARG VARIANT="16-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# RUN npm config set registry http://registry.npm.taobao.org/
# RUN npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass
# RUN npm i -g npm 
# RUN npm i -g typescript@3.7.3 webpack@4.41.4 webpack-cli@3.3.10 eslint

RUN git config --global core.autocrlf input