name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    
    - name: deploy to market
      run: |
        npm i -g vsce
        vsce publish -p ${{ secrets.VSCE_TOKEN }}
